### PR TITLE
#146: close test database connections after use

### LINKED ISSUE #146: Database connection created by tests should be closed after each run
# Issue 
Our test cases do not close connections created after each test run. 

We have a total of 70 test cases so it not a problem yet.

# Test
Quick test demo the error 

```scala
(1 to 300) foreach {
  _ =>
    val fixture = new Fixture {}
    import fixture.config.profile.api._
    fixture.run(fixture.blockDepsTable.result).futureValue
}
```
Errors the following after 214 iterations.

> java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[49.957s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.

### PR DESCRIPTION
**Pull request by simerplaha**
Resolves #146

### CODE REVIEW

File: app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala [hunk 1]
```diff
@@ -23,7 +23,7 @@ import slick.jdbc.PostgresProfile
 import slick.jdbc.PostgresProfile.api._
 
 trait DBRunner {
-  val databaseConfig: DatabaseConfig[PostgresProfile]
+  def databaseConfig: DatabaseConfig[PostgresProfile]
```
Comment (tdroxler) [inline app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala:26]: shouldn't we have a `lazy val` instead? in case someone is calling twice `databaseConfig`

**Review by tdroxler — APPROVED** [review]
Niiiice! LGTM, one minor comment

File: app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala (hunk 1 above)
Comment (simerplaha) [reply app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala:26]: Please correct me if I'm wrong but I don't think traits can have `lazy` definitions. 

If it does then the object or class that implements this trait would define it as `val`, `var`, `lazy val` or `def` and its definition would get used during runtime not the one in the trait.

Comment (simerplaha) [reply app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala:26]: Ah I think you know this stuff already. In summary it shouldn't need a lazy val 🤔

**Review by polarker — APPROVED** [review]
LGTM ❤️

File: app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala (hunk 1 above)
Comment (tdroxler) [reply app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala:26]: ah stupid me, I didn't notice it was only the definition in the trait :face_palm:
